apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: shopease
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: shopease/notification-service:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: shopease-config
          env:
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopease-secrets
                  key: smtp-password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: shopease
spec:
  selector:
    app: notification-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
