apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopease
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: shopease/order-service:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: shopease-config
          env:
            - name: DB_HOST
              value: "mysql-order"
            - name: DB_NAME
              value: "orderdb"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopease-secrets
                  key: db-password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: shopease
spec:
  selector:
    app: order-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
